//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopuliQB1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> PopId { get; set; }
        public string QBTxnId { get; set; }
        public Nullable<int> InvNo { get; set; }
        public string FirstItemName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> StudPopId { get; set; }
    }
}
