//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopuliQB1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public int PopId { get; set; }
        public string QBId { get; set; }
        public string StudName { get; set; }
        public string QBEditSeq { get; set; }
        public Nullable<int> DupNo { get; set; }
    }
}
